version: '3.8'

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vpolojie/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vpolojie/data/wordpress'

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped
    volumes: 
      - wordpress:/var/www/html/wordpress
  
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/.
    networks:
      - inception
    expose:
      - "3306"
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
  
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress/.
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/wordpress
