version: '3'

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vpolojie/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vpolojie/data/wordpress'

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped
    volumes: 
      - wordpress:/var/www/html/wordpress
  
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/.
      args:
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_ROOT_PSW=${MYSQL_ROOT_PSW}
        - MYSQL_PSW=${MYSQL_PSW}
    networks:
      - inception
    expose:
      - "3306"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
  
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress/.
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PSW=${WP_ADMIN_PSW}
        - WP_USER=${WP_USER}
        - WP_USER_PSW=${WP_USER_PSW}
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_ROOT_PSW=${MYSQL_ROOT_PSW}
        - MYSQL_PSW=${MYSQL_PSW}
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/wordpress
